# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplicate < Formula
  desc ""
  homepage "https://github.com/ilaif/goplicate"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ilaif/goplicate/releases/download/v0.1.1/goplicate_0.1.1_Darwin_arm64.tar.gz"
      sha256 "3dc6a8b5e027d1331adb0e9a1ba31ee1c855baa6f7b92e112576408fbb4c357e"

      def install
        bin.install "goplicate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilaif/goplicate/releases/download/v0.1.1/goplicate_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "9de33fa3899c486e668ec4f551d60d2d2843f1f69b816b6224d99438a5f45603"

      def install
        bin.install "goplicate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilaif/goplicate/releases/download/v0.1.1/goplicate_0.1.1_Linux_arm64.tar.gz"
      sha256 "54c25062247cbec3f6f596eba3acf485026c8b15e04186797b0dc043a0528b9c"

      def install
        bin.install "goplicate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilaif/goplicate/releases/download/v0.1.1/goplicate_0.1.1_Linux_x86_64.tar.gz"
      sha256 "a6aa0f9b6423cdb7e1ccb1a9de536cd4b37253c2e217082b5709408663a1c134"

      def install
        bin.install "goplicate"
      end
    end
  end
end
